### ISSUE TITLE
JSX  `classnames()` Support 

### ISSUE THREAD

**Issue by MaelWeb** [pranaygp/vscode-css-peek#82]
This works very well in the JSX file. But there are still some small regrets. When I use `classnames()` in JSX, it doesn't work. Is it possible to enable this in JSX?

e.g.

```less
// tese.less
.test {
    color: '#000';
}
```

```jsx
//  test.jsx
import ClassNames from "classnames";

export default function test() {
     return (<div className={ ClassNames('test') } /> )
}
```
